{{- if not .Values.backend.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "co2-calculator.fullname" . }}-backend
  labels:
    {{- include "co2-calculator.componentLabels" (dict "ctx" . "component" "backend") | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secrets.SECRET_KEY | quote }}
  {{- if .Values.database.externalSecret.enabled }}
  DATABASE_URL: ""
  DB_PASSWORD: ""
  {{- else }}
  {{- if .Values.pgbouncer.enabled }}
  DB_URL: {{ printf "postgresql+psycopg://%s:%s@%s-pgbouncer:%d/%s" .Values.database.external.username .Values.database.external.password (include "co2-calculator.fullname" .) .Values.pgbouncer.service.port .Values.database.external.database | quote }}
  {{- else if .Values.database.external.url }}
  DB_URL: {{ .Values.database.external.url | quote }}
  {{- else }}
  DB_URL: {{ printf "postgresql+psycopg://%s:%s@%s:%d/%s" .Values.database.external.username .Values.database.external.password .Values.database.external.host .Values.database.external.port .Values.database.external.database | quote }}
  {{- end }}
  DB_PASSWORD: {{ .Values.database.external.password | quote }}
  {{- end }}
{{- end }}
