name: deploy-storybook

on:
  push:
    branches:
      - dev
      - main
      - stage
      - feat/74-storybook-implementation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/epfl-enac/co2-calculator-storybook

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          file: ./frontend/Dockerfile.storybook
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/epfl-enac/co2-calculator-storybook:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy application
        run: |
          payload=$(cat <<EOF
          {
            "event_type": "update-manifest",
            "client_payload": {
              "repo_name": "co2-calculator",
              "repo_org": "EPFL-ENAC",
              "branch": "${{ github.ref_name }}",
              "images": [
                {
                  "name": "ghcr.io/epfl-enac/co2-calculator-storybook",
                  "digest": "${{ steps.build-docker-push.outputs.digest }}",
                  "ref_name": "${{ github.ref_name }}"
                }
              ],
              "create_pull_request": false
            }
          }
          EOF
          ) && \
          echo "Deploying application to dev" && \
          echo "Payload: $payload" && \
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.token }}" \
          https://api.github.com/repos/EPFL-ENAC/enack8s-app-config/dispatches \
          -d "$payload"
