name: Quality Checks

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev, 'ci-test/**']

jobs:
  
  frontent-quality:
    name: Frontent Lint/Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ">=22.0.0 < 23.0.0"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Check code formatting
        run: make lint

      - name: Quasar prepare
        run: npx quasar prepare

      - name: Type Check
        run: npx tsc --noEmit

      - name: Type Check
        run: npx vue-tsc --noEmit


  backend-quality:
    name: Backend Lint/Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Check code formatting
        run: make format-check
      
      - name: Type Check
        run: make type-check
