# name: Accessibility

# on:
#   pull_request:
#     branches: [main, dev, 'ci-test/**']
#     paths:
#       - "frontend/**"
#       - ".github/workflows/accessibility.yml"

# jobs:
#   accessibility:
#     name: Accessibility Audit
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4.4.0
#         with:
#           node-version: ">=22.0.0 < 23.0.0"
#           cache: "npm"
#           cache-dependency-path: "./frontend/package-lock.json"

#       - name: Install dependencies
#         working-directory: ./frontend
#         run: npm ci

#       # - name: Build frontend
#       # TODO: Uncomment if accessibility audit requires a build step
#       # use https://www.npmjs.com/package/@axe-core/playwright
#       # build on existing test workflow
